## Difference between numpy array and list:
1. less memory
2. fast 
3. convenient

In [13]:
import numpy as np

In [3]:
## 1-dimensional array
a=np.array([1,2,3,4,5])
print(a.ndim)

1


In [26]:
a1=np.array([[1,2,3],[4,5,6],[6,7,8],[8,9,10]])
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [7]:
a1.ndim

2

In [8]:
a1.shape


(3, 3)

In [11]:
a.shape

(5,)

In [13]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0]) ##rows
print(a2.shape[1]) ##columns

4
3


In [6]:
import numpy as np
a3=np.array([],dtype="int32")

In [7]:
a3=np.append(a3,int(input()))
a3

12


array([12])

In [8]:
a3=np.append(a3,[23,24,85,79,58])
a3

array([12, 23, 24, 85, 79, 58])

In [27]:
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

## slicing:

In [16]:
print(a3[3])

85


In [28]:
print(a1[1,1])

5


In [29]:
print(a1[2:,:])

[[ 6  7  8]
 [ 8  9 10]]


In [30]:
print(a1[2:,0:2])

[[6 7]
 [8 9]]


In [37]:
print(a1[0:,0:2])

[[1 2]
 [4 5]
 [6 7]
 [8 9]]


In [41]:
print(a1[0:,:4])

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


## indexing with boolean array

In [43]:
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [44]:
result =(arr1%2==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

## Appending array

In [48]:
import numpy as np
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [49]:
print(np.hstack((arr1,arr2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [50]:
arr3=np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
print(arr3.size)
print(arr3.itemsize)
print(arr3.dtype)
print(arr3.ndim)
print(arr3.shape)


9
4
int32
2
(3, 3)


## Functions:
1. zeros()
2. ones()
3. full()
4. eye()


In [62]:
import numpy as np
z=np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [63]:
import numpy as np
z=np.ones((3,3),dtype="int32")
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [65]:
f=np.full((3,3),"rahul")
print(f)

[['rahul' 'rahul' 'rahul']
 ['rahul' 'rahul' 'rahul']
 ['rahul' 'rahul' 'rahul']]


In [67]:
##eye
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])