In [23]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

28
0.4748043695691988


In [24]:
#creating n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[56 39 50]
[[ 9  6 60 67]
 [ 0 81  1  5]
 [36 88 29 98]]
[[[16 64]
  [28 13]
  [99 81]
  [80 22]]

 [[36 32]
  [ 3 79]
  [95 35]
  [57 69]]

 [[13  3]
  [78  3]
  [96  5]
  [44 65]]]


In [25]:
#ravel() flattens array elements
a = random.randint(100,size=(3,2))
a

array([[84, 42],
       [24, 39],
       [ 8, 95]])

In [26]:
#ravel() flattens array elements
a = random.randint(100,size=(3,2)).ravel()
a

array([33, 58, 34, 23, 54, 24])

In [27]:
#single element will be selected
random.choice(a)

24

In [28]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 4, 3, 2],
       [1, 2, 4, 1],
       [5, 1, 1, 3],
       [1, 1, 5, 3]])

### pandas:
1. Data manipulation,analysis and cleaning
2. we can work with Tabular,Unlabelled data

### Creating a DataFrame
1. using 2 dictionaries
2. simple dictionary --> DataFrame
3. using Series

In [29]:
#using 2 dictionaries
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [2]:
#simple dictionary --> DataFrame
d1 = {"Name":["preeti","mounika","sumathi"],"Address":["hyd","adb","AP"]}
df1 = pd.DataFrame(d1)
df1

Name Address
0   preeti     hyd
1  mounika     adb
2  sumathi      AP

In [3]:
#using Series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

### Selecting the data from the DataFrame:
1. loc --> Row and Column labels
2. iloc --> Row and Column index

In [4]:
type(df3)

pandas.core.frame.DataFrame

In [5]:
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [6]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

In [7]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [8]:
#Extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78

In [9]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [10]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame

In [11]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [12]:
#returns no.of rows and columns of the DataFrame
df3.shape

(10, 3)

In [13]:
#returns columns of the DataFrame
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [14]:
#returns rows indexes  of the DataFrame
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [15]:
#First 5 rows
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e

In [16]:
#First n rows
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [17]:
#last 5 rows
df3.tail()

column1  column2 column3
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [18]:
#returns last n rows
df3.tail(2)

column1  column2 column3
8        9     67.4       i
9       10     23.0       j

In [19]:
#returns a random row from the DataFrame
df3.sample()

column1  column2 column3
4        5     67.4       e

In [20]:
#returns a n random rows from the DataFrame
df3.sample(2)

column1  column2 column3
9       10     23.0       j
8        9     67.4       i

In [21]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [22]:
#Renaming the column headers
df3 = df3.rename(columns={"column1":"First",
                          "column2":"Second",
                          "column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j